import type { Failure, Requirement, Scenario } from "./types";

export function exportKiroFixTasks(failures: Failure[], requirements: Requirement[], scenarios: Scenario[]): string {
  const byReq = new Map(requirements.map((requirement) => [requirement.id, requirement]));
  const byScenario = new Map(scenarios.map((scenario) => [scenario.id, scenario]));
  const lines = [
    "# Agent Hardening Tasks",
    "",
    "Generated by VoiceGauntlet from failing ElevenLabs voice-agent simulations.",
    ""
  ];

  failures.forEach((failure, index) => {
    const requirement = byReq.get(failure.requirementId);
    const scenario = byScenario.get(failure.scenarioId);
    lines.push(`- [ ] ${index + 1}. Fix ${failure.requirementId}: ${requirement?.title ?? failure.title}`);
    lines.push(`  - Scenario: ${scenario?.title ?? failure.scenarioId}`);
    lines.push(`  - Severity: ${failure.severity}`);
    lines.push(`  - Evidence: ${failure.evidence}`);
    lines.push("  - Acceptance: rerun VoiceGauntlet and confirm this scenario passes with no regression failures.");
    lines.push("");
  });

  if (failures.length === 0) {
    lines.push("- [x] No hardening tasks required. VoiceGauntlet suite is green.");
  }

  return lines.join("\n");
}
